apiVersion : apps/v1
kind: Deployment
metadata:
  name: my_app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my_app
  template:
    metadata:
      labels:
        app: paulespinoks
    spec:
      containers:
        - name: paulespinoks
          image: mycontainerregistryespino.azurecr.io/paulespinoks
          ports:
          - containerPort: 8080
